# Generated by Django 3.1.7 on 2021-07-06 05:25

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('coup_id', models.AutoField(primary_key=True, serialize=False)),
                ('coup_name', models.CharField(max_length=100)),
                ('start_date', models.DateField(default=datetime.date.today)),
                ('end_date', models.DateField(default=datetime.date.today)),
            ],
        ),
        migrations.CreateModel(
            name='CouponHandling',
            fields=[
                ('username', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('timestamp_login', models.DateTimeField(blank=True, null=True)),
                ('timestamp_logout', models.DateTimeField(blank=True, null=True)),
                ('total_usage', models.DateTimeField(blank=True, null=True)),
                ('user', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('locid', models.AutoField(primary_key=True, serialize=False)),
                ('ltype', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('vid', models.AutoField(primary_key=True, serialize=False)),
                ('vtype', models.CharField(max_length=100)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='View',
            fields=[
                ('viewid', models.AutoField(primary_key=True, serialize=False)),
                ('cid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Login.customer')),
                ('locid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Coupon.location')),
            ],
        ),
        migrations.CreateModel(
            name='Get',
            fields=[
                ('gid', models.AutoField(primary_key=True, serialize=False)),
                ('coupon_unique_code', models.CharField(max_length=100)),
                ('status', models.BooleanField(default=False)),
                ('cid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Login.login')),
                ('coup_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Coupon.coupon')),
            ],
        ),
    ]
