# Generated by Django 3.1.7 on 2021-07-06 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Coupon', '0002_auto_20210706_1106'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='get',
            name='cid',
        ),
        migrations.AddField(
            model_name='get',
            name='username',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
