# Generated by Django 3.1.7 on 2021-07-06 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Coupon', '0003_auto_20210706_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='get',
            name='coupon_unique_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
