# Generated by Django 3.1.7 on 2021-07-06 05:25

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('hid', models.AutoField(primary_key=True, serialize=False)),
                ('himage', models.CharField(blank=True, max_length=100, null=True)),
                ('hname', models.CharField(blank=True, max_length=100, null=True)),
                ('lat', models.CharField(blank=True, max_length=100, null=True)),
                ('lon', models.CharField(blank=True, max_length=100, null=True)),
                ('hlocation', models.CharField(max_length=100)),
                ('contact_number', models.CharField(max_length=500)),
                ('haddress', models.CharField(max_length=100)),
                ('hprice', models.FloatField(blank=True, null=True)),
                ('keywords', models.CharField(max_length=100)),
                ('hrating', models.CharField(max_length=100)),
                ('hcategory', models.CharField(max_length=100)),
                ('hmaplink', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tourist',
            fields=[
                ('tid', models.AutoField(primary_key=True, serialize=False)),
                ('timage', models.CharField(blank=True, max_length=100, null=True)),
                ('tname', models.CharField(max_length=100)),
                ('lat', models.CharField(blank=True, max_length=100, null=True)),
                ('lon', models.CharField(blank=True, max_length=100, null=True)),
                ('tlocation', models.CharField(max_length=100)),
                ('contact_number', models.CharField(max_length=500)),
                ('taddress', models.CharField(max_length=100)),
                ('tprice', models.FloatField(blank=True, null=True)),
                ('keywords', models.CharField(max_length=100)),
                ('trating', models.CharField(max_length=100)),
                ('tcategory', models.CharField(max_length=100)),
                ('tmaplink', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rents',
            fields=[
                ('rid', models.AutoField(primary_key=True, serialize=False)),
                ('rnumber', models.CharField(max_length=100)),
                ('rental_date', models.DateField(default=datetime.date.today)),
                ('return_date', models.DateField(default=datetime.date.today)),
                ('license', models.CharField(max_length=100)),
                ('no_of_days', models.IntegerField()),
                ('cid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Login.customer')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Rent.hotel')),
                ('oid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Login.owner')),
            ],
        ),
    ]
