# Generated by Django 3.1.7 on 2021-07-15 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rent', '0004_auto_20210716_0153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='himage',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='tourist',
            name='timage',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
