# Generated by Django 3.1.7 on 2021-07-15 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rent', '0005_auto_20210716_0158'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='tourist',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
