# Generated by Django 3.1.7 on 2021-07-06 05:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Login', '0001_initial'),
        ('Coupon', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lend',
            fields=[
                ('lid', models.AutoField(primary_key=True, serialize=False)),
                ('date_upload', models.DateField(auto_now_add=True)),
                ('date_of_return', models.DateField(blank=True, null=True)),
                ('valid', models.BooleanField(default=True)),
                ('cid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Login.customer')),
                ('oid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Login.owner')),
                ('vid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Coupon.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('car_id', models.AutoField(primary_key=True, serialize=False)),
                ('cnumber', models.CharField(max_length=100, unique=True)),
                ('seating_capacity', models.IntegerField()),
                ('ctype', models.CharField(max_length=100)),
                ('cmodel', models.CharField(max_length=100)),
                ('cname', models.CharField(max_length=100)),
                ('crating', models.FloatField()),
                ('cprice', models.FloatField()),
                ('cimage', models.FileField(blank=True, null=True, upload_to='')),
                ('transmission', models.CharField(blank=True, max_length=500, null=True)),
                ('description', models.TextField(blank=True, max_length=1000, null=True)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('oid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Login.owner')),
                ('vid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Coupon.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='Bike',
            fields=[
                ('bike_id', models.AutoField(primary_key=True, serialize=False)),
                ('bnumber', models.CharField(max_length=100, unique=True)),
                ('btype', models.CharField(blank=True, max_length=100, null=True)),
                ('bmodel', models.CharField(blank=True, max_length=100, null=True)),
                ('bname', models.CharField(blank=True, max_length=100, null=True)),
                ('brating', models.FloatField(blank=True, null=True)),
                ('bprice', models.FloatField(blank=True, null=True)),
                ('bimage', models.FileField(blank=True, null=True, upload_to='')),
                ('description', models.TextField(blank=True, max_length=1000, null=True)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('oid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Login.owner')),
                ('vid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Coupon.vehicle')),
            ],
        ),
    ]
