# Generated by Django 3.1.7 on 2021-07-12 22:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Lend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Approval',
            fields=[
                ('ap_id', models.AutoField(primary_key=True, serialize=False)),
                ('approve', models.BooleanField(default=True)),
                ('lid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Lend.lend')),
            ],
        ),
    ]
