# Generated by Django 3.1.7 on 2021-07-13 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lend', '0002_approval'),
    ]

    operations = [
        migrations.AddField(
            model_name='approval',
            name='username',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='approval',
            name='approve',
            field=models.BooleanField(default=False),
        ),
    ]
