# Generated by Django 3.1.7 on 2021-07-28 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Coupon', '0004_auto_20210706_1304'),
        ('Lend', '0004_auto_20210716_0438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bike',
            name='vid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Coupon.vehicle'),
        ),
        migrations.AlterField(
            model_name='car',
            name='vid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Coupon.vehicle'),
        ),
    ]
